# Generated by Django 4.2.1 on 2023-08-24 17:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import functools
import phonenumber_field.modelfields
import utils.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50)),
                ('store_description', models.TextField(blank=True)),
                ('account_status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('store_logo', models.ImageField(blank=True, upload_to=functools.partial(utils.helpers.uploaded_file_directory_path, *('store_logo/',), **{}))),
                ('cached_average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('number_of_sales', models.IntegerField(default=0)),
                ('provider_type', models.CharField(choices=[('STORE', 'Store'), ('INDIVIDUAL', 'Individual'), ('JUNKYARD', 'Junkyard'), ('WHOLESALER', 'Wholesaler'), ('MANUFACTURER', 'Manufacturer')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to=functools.partial(utils.helpers.uploaded_file_directory_path, *('profile_pic/',), **{}))),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('sign_up_date', models.DateTimeField(auto_now_add=True)),
                ('last_login_date', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='accounts.provider')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.consumer')),
            ],
        ),
        migrations.AddField(
            model_name='provider',
            name='userprofile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
