# Generated by Django 5.0.4 on 2024-05-07 10:42

import django.core.validators
import functools
import utils.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, max_length=50)),
                ('store_description', models.TextField(blank=True)),
                ('account_status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to=functools.partial(utils.helpers.uploaded_file_directory_path, *('store_logo/',), **{}))),
                ('cached_average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('number_of_sales', models.IntegerField(default=0)),
                ('provider_type', models.CharField(blank=True, choices=[('STORE', 'Store'), ('INDIVIDUAL', 'Individual'), ('JUNKYARD', 'Junkyard'), ('WHOLESALER', 'Wholesaler'), ('MANUFACTURER', 'Manufacturer')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('PROVIDER', 'Provider'), ('CONSUMER', 'Consumer')], default='PROVIDER', max_length=20)),
                ('profile_pic', models.ImageField(blank=True, upload_to=functools.partial(utils.helpers.uploaded_file_directory_path, *('profile_pic/',), **{}))),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('sign_up_date', models.DateTimeField(auto_now_add=True)),
                ('last_login_date', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
