# Generated by Django 5.0.4 on 2024-05-07 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('components', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='cart',
            field=models.ManyToManyField(related_name='cart', to='components.autopart'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlist', to='components.autopart'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='favorite_providers',
            field=models.ManyToManyField(related_name='favorite_providers', to='accounts.provider'),
        ),
        migrations.AddField(
            model_name='rating',
            name='rated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='accounts.provider'),
        ),
        migrations.AddField(
            model_name='rating',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.consumer'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provider',
            name='userprofile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='userprofile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
