# Generated by Django 4.2.1 on 2023-08-24 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='cart',
            field=models.ManyToManyField(related_name='cart', to='components.autopart'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='favorite_providers',
            field=models.ManyToManyField(related_name='favorite_providers', to='accounts.provider'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='userprofile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlist', to='components.autopart'),
        ),
    ]
