# Generated by Django 5.0.4 on 2024-04-30 16:00

import functools
import utils.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='provider_type',
            field=models.CharField(blank=True, choices=[('STORE', 'Store'), ('INDIVIDUAL', 'Individual'), ('JUNKYARD', 'Junkyard'), ('WHOLESALER', 'Wholesaler'), ('MANUFACTURER', 'Manufacturer')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='store_logo',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(utils.helpers.uploaded_file_directory_path, *('store_logo/',), **{})),
        ),
    ]
