# Generated by Django 4.2.1 on 2023-08-27 03:51

from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension
from django.contrib.postgres.indexes import GinIndex
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('stock', models.IntegerField(null=True)),
                ('image', models.ImageField(null=True, upload_to='component_images')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.provider')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('ENGINE', 'Engine'), ('TRANSMISSION', 'Transmission'), ('SUSPENSION', 'Suspension'), ('BRAKES', 'Brakes'), ('ELECTRICAL', 'Electrical'), ('BODY', 'Body'), ('INTERIOR', 'Interior'), ('TIRES', 'Tires'), ('WHEELS', 'Wheels'), ('ACCESSORIES', 'Accessories')], max_length=20)),
                ('vehicle_make', models.CharField(blank=True, max_length=100)),
                ('vehicle_model', models.CharField(blank=True, max_length=100)),
                ('vehicle_year', models.CharField(blank=True, max_length=100)),
                ('condition', models.CharField(blank=True, choices=[('NEW', 'New'), ('USED', 'Used'), ('REFURBISHED', 'Refurbished')], max_length=100)),
                ('oem_number', models.CharField(blank=True, max_length=100)),
                ('upc_number', models.CharField(blank=True, max_length=100)),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='components.component')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='autopart',
            index=GinIndex(fields=['category'], name='autopart_category_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='autopart',
            index=GinIndex(fields=['condition'], name='autopart_condition_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='component',
            index=GinIndex(fields=['name'], name='component_name_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='component',
            index=GinIndex(fields=['manufacturer'], name='component_manufacturer_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='component',
            index=GinIndex(fields=['description'], name='component_description_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
