# Generated by Django 5.0.4 on 2024-05-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_remove_autopart_autopart_category_gin_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopart',
            name='category',
            field=models.CharField(blank=True, choices=[('ACCESSORIES', 'Accessories'), ('AIR_CONDITIONING_AND_HEATING', 'Air Conditioning & Heating'), ('ALTERNATORS_AND_STARTERS', 'Alternators & Starters'), ('BATTERY_AND_ACCESSORIES', 'Battery & Accessories'), ('BEARING_AND_SEALS', 'Bearing & Seals'), ('BELTS_AND_HOSES', 'Belts & Hoses'), ('BRAKES', 'Brakes'), ('CV_DRIVESHAFT_AND_AXLE', 'CV, Driveshaft & Axle'), ('CHASSIS_AND_STEERING', 'Chassis & Steering'), ('DETAILING', 'Detailing'), ('ENGINE_COOLING', 'Engine Cooling'), ('ENGINE_SENSORS_AND_EMISSIONS', 'Engine Sensors & Emissions'), ('ENGINES_AND_TRANSMISSIONS', 'Engines & Transmissions'), ('EXHAUST', 'Exhaust'), ('FILTERS', 'Filters'), ('FUEL_DELIVERY', 'Fuel Delivery'), ('GASKETS', 'Gaskets'), ('HARDWARE_AND_FASTENERS', 'Hardware & Fasteners'), ('HEAVY_DUTY_AG_AND_FLEET', 'Heavy Duty, Ag & Fleet'), ('IGNITION_AND_TUNE_UP', 'Ignition & Tune-Up'), ('LAWN_AND_GARDEN', 'Lawn & Garden'), ('LIGHTING_AND_ELECTRICAL', 'Lighting & Electrical'), ('MARINE_AND_BOAT', 'Marine & Boat'), ('MORE_POWERSPORT', 'More Powersport'), ('OIL_CHEMICALS_AND_FLUIDS', 'Oil, Chemicals & Fluids'), ('PAINT_AND_BODY', 'Paint & Body'), ('PERFORMANCE', 'Performance'), ('RECREATIONAL_VEHICLE', 'Recreational Vehicle'), ('SHOCKS_AND_STRUTS', 'Shocks & Struts'), ('TIRE_AND_WHEEL', 'Tire & Wheel'), ('TOOLS_AND_EQUIPMENT', 'Tools & Equipment'), ('TRUCK_TOWING_AND_JEEP', 'Truck, Towing & Jeep'), ('TURBOCHARGER_AND_SUPERCHARGER', 'Turbocharger & Supercharger'), ('WIPERS_AND_COMPONENTS', 'Wipers & Components')], max_length=100),
        ),
    ]
