# Generated by Django 5.0.4 on 2024-05-06 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_category_alter_autopart_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopart',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.category'),
        ),
    ]
